### ISSUE TITLE
No mention of requirements needed to have installed

### ISSUE THREAD

**Issue by jsjohnst** [AllenDowney/BayesMadeSimple#1]
Probably should mention that the following is needed to be installed:

```
matplotlib
numpy
scipy
pandas
```

in the readme and/or your website to make it easier to get going.

**Comment by AllenDowney** [comment]
This info is on the tutorial web site, which is here: https://sites.google.com/site/simplebayes/

I added a link from the README.

Thanks for the suggestion!

**Comment by jsjohnst** [comment]
Might I suggest adding a requirements.txt to the repo too? That's the standard convention for python. I sadly looked at the website twice for requirements when I hit the first missing one, but missed the sentence both times. As such, had to trial and error to get it. Had I not watched your great talk, I might not have been as persistent.
