### ISSUE TITLE
add_dist failed at statement "twice = d6.add_dist(d6)" in 01_cookie.ipynb

### ISSUE THREAD

**Issue by vigneshmraj** [AllenDowney/BayesMadeSimple#12]
The error:
AttributeError: 'Pmf' object has no attribute 'add_dist'

Looks like you have removed add_dist from the Pmf class in the latest version of the empyrical_dist and that seems to break the code in the notebook.

My questions/requests to you are:
1. Did you change the empyrical_dist from empiricaldist module? Are they 2 different packages? Is one a later version of the other?
2. If you have changed the name/code of the module, could you please make necessary changes in the jupyter notebook files as well, so that it is easier for people who are following your lecture on youtube?

**Comment by vigneshmraj** [comment]
Looks like this could be an issue with Pipenv virtualenv wrapper! sorry about the confusion!

**Comment by AllenDowney** [comment]
Sorry for this hassle -- this API has been in flux.
