### ISSUE TITLE
Can't calculate credible intervals nor quantiles

### ISSUE THREAD

**Issue by pedrolimase** [AllenDowney/BayesMadeSimple#16]
When I try to do it, I get the following error:

> NotImplementedError                       Traceback (most recent call last)
> <ipython-input-28-f32307f4bd72> in <module>
>       1 for i, b in enumerate(beliefs):
> ----> 2     print(b.mean(), b.credible_interval(0.9))
> 
> c:\users\...\appdata\local\programs\python\python36-32\lib\site-packages\empiricaldist\empiricaldist.py in credible_interval(self, p)
>     716         tail = (1 - p) / 2
>     717         ps = [tail, 1 - tail]
> --> 718         return self.quantile(ps)
>     719 
>     720     @staticmethod
> 
> c:\users\...\appdata\local\programs\python\python36-32\lib\site-packages\empiricaldist\empiricaldist.py in quantile(self, ps, **kwargs)
>     137         :return: float
>     138         """
> --> 139         return self.make_cdf().quantile(ps, **kwargs)
>     140 
>     141     def choice(self, *args, **kwargs):
> 
> c:\users\...\appdata\local\programs\python\python36-32\lib\site-packages\empiricaldist\empiricaldist.py in inverse(self, **kwargs)
>     846         )
>     847 
> --> 848         interp = interp1d(self.ps, self.qs, **kwargs)
>     849         return interp
>     850 
> 
> c:\users\...\appdata\local\programs\python\python36-32\lib\site-packages\scipy\interpolate\interpolate.py in __init__(self, x, y, kind, axis, copy, bounds_error, fill_value, assume_sorted)
>     443         elif kind not in ('linear', 'nearest'):
>     444             raise NotImplementedError("%s is unsupported: Use fitpack "
> --> 445                                       "routines for other types." % kind)
>     446         x = array(x, copy=self.copy)
>     447         y = array(y, copy=self.copy)
> 
> NotImplementedError: next is unsupported: Use fitpack routines for other types.

**Comment by AllenDowney** [comment]
What's `b`?  Is this one of my examples or your code?

**Comment by WHoZ-II** [comment]
Sorry, I forgot to mention it. It's in the '04_bandit.ipynb' notebook, although I got the same error before.

The code is the exact same you used.
`b` is each Pmf on the set of `beliefs` about the slot machines.

**Comment by AllenDowney** [comment]
This runs on my up-to-date Anaconda installation and on Colab (which is not as up-to-date):

https://colab.research.google.com/github/AllenDowney/BayesMadeSimple/blob/master/04_bandit_soln.ipynb

So I think you have an older package. interp1d is from SciPy, so maybe try updating that.

**Comment by WHoZ-II** [comment]
I have Anaconda but I wasn't able to install the empyrical-dist package, so I used base Python.
Now I figured out I can import it from the file. Thanks, Allen!

**Comment by AllenDowney** [comment]
Ok, good luck!
